package signature

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

type fixture struct {
	Secret     string `json:"secret"`
	Body       string `json:"body"`
	Inbound    string `json:"inbound"`
	Ts         int64  `json:"ts"`
	DeliveryId string `json:"deliveryId"`
	Outbound   string `json:"outbound"`
}

// Fixture generated by node with ari's exact HMAC construction; see testdata/signatures.json.
func loadFixture(t *testing.T) fixture {
	t.Helper()
	raw, err := os.ReadFile("../../testdata/signatures.json")
	if err != nil {
		t.Fatal(err)
	}
	var f fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatal(err)
	}
	return f
}

func TestVerifyInboundNodeVector(t *testing.T) {
	f := loadFixture(t)
	if !VerifyInbound(f.Secret, []byte(f.Body), f.Inbound) {
		t.Fatal("node-computed signature rejected")
	}
	if !VerifyInbound(f.Secret, []byte(f.Body), "  "+strings.ToUpper(f.Inbound)+" ") {
		t.Fatal("trimmed uppercase header rejected; ari accepts case-insensitive hex")
	}
	if VerifyInbound(f.Secret, []byte(f.Body), "") {
		t.Fatal("empty header accepted")
	}
	if VerifyInbound(f.Secret, []byte(f.Body+"x"), f.Inbound) {
		t.Fatal("modified body accepted")
	}
	if VerifyInbound("wrong", []byte(f.Body), f.Inbound) {
		t.Fatal("wrong secret accepted")
	}
}

func TestSignOutboundNodeVector(t *testing.T) {
	f := loadFixture(t)
	got := SignOutbound(f.Secret, f.DeliveryId, f.Ts, []byte(f.Body))
	if got != f.Outbound {
		t.Fatalf("outbound signature %s, want node-computed %s", got, f.Outbound)
	}
}
