package signature

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

type fixture struct {
	Secret     string `json:"secret"`
	Body       string `json:"body"`
	Inbound    string `json:"inbound"`
	Ts         int64  `json:"ts"`
	DeliveryId string `json:"deliveryId"`
	Outbound   string `json:"outbound"`
}

// Fixture generated by node with ari's exact HMAC construction; see testdata/signatures.json.
func loadFixture(t *testing.T) fixture {
	t.Helper()
	raw, err := os.ReadFile("../../testdata/signatures.json")
	if err != nil {
		t.Fatal(err)
	}
	var f fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatal(err)
	}
	return f
}

func TestVerifyInboundNodeVector(t *testing.T) {
	f := loadFixture(t)
	if !VerifyInbound(f.Secret, []byte(f.Body), f.Inbound) {
		t.Fatal("node-computed signature rejected")
	}
	if !VerifyInbound(f.Secret, []byte(f.Body), "  "+strings.ToUpper(f.Inbound)+" ") {
		t.Fatal("trimmed uppercase header rejected; ari accepts case-insensitive hex")
	}
	if VerifyInbound(f.Secret, []byte(f.Body), "") {
		t.Fatal("empty header accepted")
	}
	if VerifyInbound(f.Secret, []byte(f.Body+"x"), f.Inbound) {
		t.Fatal("modified body accepted")
	}
	if VerifyInbound("wrong", []byte(f.Body), f.Inbound) {
		t.Fatal("wrong secret accepted")
	}
}

func signTimestamped(secret string, ts int64, body string) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(strconv.FormatInt(ts, 10) + "." + body))
	return hex.EncodeToString(mac.Sum(nil))
}

func TestVerifyInboundAt(t *testing.T) {
	now := time.Unix(1_750_000_000, 0)
	secret, body := "whsec_test", `{"external_id":"p1"}`
	ts := now.Unix() - 120
	sig := signTimestamped(secret, ts, body)

	if !VerifyInboundAt(secret, []byte(body), sig, strconv.FormatInt(ts, 10), now) {
		t.Fatal("timestamped signature inside the window rejected")
	}
	if !VerifyInboundAt(secret, []byte(body), sig, " "+strconv.FormatInt(ts, 10)+" ", now) {
		t.Fatal("surrounding whitespace on the timestamp must be tolerated")
	}
	if VerifyInboundAt(secret, []byte(body), sig, "", now) {
		t.Fatal("a timestamped signature must not verify as a body-only one")
	}
	if VerifyInboundAt(secret, []byte(body), sig, strconv.FormatInt(ts+1, 10), now) {
		t.Fatal("a timestamp the signature does not cover accepted")
	}
	if VerifyInboundAt(secret, []byte(body+"x"), sig, strconv.FormatInt(ts, 10), now) {
		t.Fatal("modified body accepted")
	}
	if VerifyInboundAt(secret, []byte(body), sig, "not-a-number", now) {
		t.Fatal("non-integer timestamp accepted")
	}
	if VerifyInboundAt(secret, []byte(body), sig, "1750000000.5", now) {
		t.Fatal("fractional timestamp accepted")
	}

	for _, skew := range []int64{-301, 301, -86400, 86400} {
		stale := now.Unix() + skew
		if VerifyInboundAt(secret, []byte(body), signTimestamped(secret, stale, body), strconv.FormatInt(stale, 10), now) {
			t.Fatalf("timestamp %ds from now accepted", skew)
		}
	}
	for _, skew := range []int64{-300, 300} {
		edge := now.Unix() + skew
		if !VerifyInboundAt(secret, []byte(body), signTimestamped(secret, edge, body), strconv.FormatInt(edge, 10), now) {
			t.Fatalf("timestamp %ds from now, on the edge of the window, rejected", skew)
		}
	}

	legacy := loadFixture(t)
	if !VerifyInboundAt(legacy.Secret, []byte(legacy.Body), legacy.Inbound, "", now) {
		t.Fatal("legacy body-only signature without a timestamp header rejected")
	}
	if VerifyInboundAt(legacy.Secret, []byte(legacy.Body), legacy.Inbound, strconv.FormatInt(now.Unix(), 10), now) {
		t.Fatal("a body-only signature must not verify once the sender claims a timestamp")
	}
}

func TestSignOutboundNodeVector(t *testing.T) {
	f := loadFixture(t)
	got := SignOutbound(f.Secret, f.DeliveryId, f.Ts, []byte(f.Body))
	if got != f.Outbound {
		t.Fatalf("outbound signature %s, want node-computed %s", got, f.Outbound)
	}
}
