package cryptobox

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
)

// Fixture generated by node with ari's exact crypto.ts algorithm; see testdata/cryptoblob.json.
func TestDecryptNodeBlob(t *testing.T) {
	raw, err := os.ReadFile("../../testdata/cryptoblob.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		KeyBase64 string `json:"keyBase64"`
		Blob      string `json:"blob"`
		Plaintext string `json:"plaintext"`
	}
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatal(err)
	}
	key, err := base64.StdEncoding.DecodeString(fixture.KeyBase64)
	if err != nil {
		t.Fatal(err)
	}
	codec, err := New(key)
	if err != nil {
		t.Fatal(err)
	}
	got, err := codec.Decrypt(fixture.Blob)
	if err != nil {
		t.Fatal(err)
	}
	if got != fixture.Plaintext {
		t.Fatalf("decrypted %q, want %q", got, fixture.Plaintext)
	}
}

func TestRoundTrip(t *testing.T) {
	codec, err := New(make([]byte, 32))
	if err != nil {
		t.Fatal(err)
	}
	blob, err := codec.Encrypt("hello world é漢字")
	if err != nil {
		t.Fatal(err)
	}
	got, err := codec.Decrypt(blob)
	if err != nil {
		t.Fatal(err)
	}
	if got != "hello world é漢字" {
		t.Fatalf("round trip got %q", got)
	}
}

func TestDecryptRejectsTamper(t *testing.T) {
	codec, _ := New(make([]byte, 32))
	blob, _ := codec.Encrypt("secret")
	if _, err := codec.Decrypt(blob[:len(blob)-4] + "AAA="); err == nil {
		t.Fatal("tampered blob decrypted without error")
	}
	if _, err := codec.Decrypt("not-a-blob"); err == nil {
		t.Fatal("malformed blob decrypted without error")
	}
}

func TestNewRejectsBadKey(t *testing.T) {
	if _, err := New(make([]byte, 16)); err == nil {
		t.Fatal("16-byte key accepted")
	}
}
